 import { ButtonType } from "./Components/CourseCard/page";


export const liveClass = [
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 1",
      description: "Learn with this class. Simple and effective.",
      teacher: "Saman Silva",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.LIVE,
      price: 5200,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 2",
      description: "Enhance your skills with detailed lessons.",
      teacher: "Kamal Perera",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.LIVE,
      price: 4500,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 3",
      description: "Achieve your goals with expert guidance.",
      teacher: "Nimal Fernando",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.LIVE,
      price: 6000,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 4",
      description: "Interactive and engaging classes for all.",
      teacher: "Amara Silva",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.LIVE,
      price: 3500,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 5",
      description: "Master new skills with personalized classes.",
      teacher: "Rajitha Perera",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.LIVE,
      price: 7000,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 6",
      description: "A deep dive into essential techniques.",
      teacher: "Mala Jayasuriya",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.LIVE,
      price: 4800,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 7",
      description: "Learn interactively with experienced tutors.",
      teacher: "Ruwan De Silva",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.LIVE,
      price: 5600,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 8",
      description: "Simple lessons for complex subjects.",
      teacher: "Nishan Perera",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.LIVE,
      price: 4200,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 9",
      description: "Detailed guidance for every student.",
      teacher: "Kumara Silva",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.LIVE,
      price: 5400,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 10",
      description: "Get inspired with the best lessons.",
      teacher: "Indika Rathnayake",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.LIVE,
      price: 6200,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 11",
      description: "Practical classes for real-world skills.",
      teacher: "Dilshan Fernando",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.LIVE,
      price: 3900,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 12",
      description: "Transform your learning experience today.",
      teacher: "Shehan Silva",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.LIVE,
      price: 4500,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 13",
      description: "Achieve excellence with expert tutoring.",
      teacher: "Nadeera Perera",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.LIVE,
      price: 5800,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 14",
      description: "Tailored lessons for unique learning needs.",
      teacher: "Chathura Gunawardena",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.LIVE,
      price: 4900,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 15",
      description: "Interactive sessions with modern techniques.",
      teacher: "Amila Silva",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.LIVE,
      price: 5200,
    },
  ];

  export const pastClass = [
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 1",
      description: "Achieve your goals with expert guidance.",
      teacher: "Nimal Fernando",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.PAST,
      price: 6000,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 2",
      description: "Interactive and engaging classes for all.",
      teacher: "Amara Silva",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.PAST,
      price: 3500,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 3",
      description: "Achieve your goals with expert guidance.",
      teacher: "Nimal Fernando",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.PAST,
      price: 6000,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 4",
      description: "Learn with this class. Simple and effective.",
      teacher: "Saman Silva",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.PAST,
      price: 5200,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 5",
      description: "Enhance your skills with detailed lessons.",
      teacher: "Kamal Perera",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.PAST,
      price: 4500,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 6",
      description: "Interactive and engaging classes for all.",
      teacher: "Amara Silva",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.PAST,
      price: 3500,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 7",
      description: "Achieve your goals with expert guidance.",
      teacher: "Nimal Fernando",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.PAST,
      price: 6000,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 8",
      description: "Learn with this class. Simple and effective.",
      teacher: "Saman Silva",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.PAST,
      price: 5200,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 9",
      description: "Enhance your skills with detailed lessons.",
      teacher: "Kamal Perera",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.PAST,
      price: 4500,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 10",
      description: "Interactive and engaging classes for all.",
      teacher: "Amara Silva",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.PAST,
      price: 3500,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 11",
      description: "Achieve your goals with expert guidance.",
      teacher: "Nimal Fernando",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.PAST,
      price: 6000,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 12",
      description: "Learn with this class. Simple and effective.",
      teacher: "Saman Silva",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.PAST,
      price: 5200,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 13",
      description: "Enhance your skills with detailed lessons.",
      teacher: "Kamal Perera",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.PAST,
      price: 4500,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 14",
      description: "Interactive and engaging classes for all.",
      teacher: "Amara Silva",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.PAST,
      price: 3500,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 15",
      description: "Achieve your goals with expert guidance.",
      teacher: "Nimal Fernando",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.PAST,
      price: 6000,
    },
  ];
  
  export const purchaseClass = [
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 1",
      description: "Learn with this class. Simple and effective.",
      teacher: "Saman Silva",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.PURCHASE,
      price: 5200,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 2",
      description: "Enhance your skills with detailed lessons.",
      teacher: "Kamal Perera",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.PURCHASE,
      price: 4500,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 3",
      description: "Achieve your goals with expert guidance.",
      teacher: "Nimal Fernando",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.PURCHASE,
      price: 6000,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 4",
      description: "Interactive and engaging classes for all.",
      teacher: "Amara Silva",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.PURCHASE,
      price: 3500,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 5",
      description: "Master new techniques with ease.",
      teacher: "Anushka Perera",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.PURCHASE,
      price: 4800,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 6",
      description: "Unlock your potential with this course.",
      teacher: "Ravi Kumar",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.PURCHASE,
      price: 5200,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 7",
      description: "Gain practical knowledge and hands-on experience.",
      teacher: "Ayesha Gomes",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.PURCHASE,
      price: 5600,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 8",
      description: "Advance your career with expert training.",
      teacher: "Sarath Nimal",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.PURCHASE,
      price: 4000,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 9",
      description: "Learn the secrets to success in your field.",
      teacher: "Himali Ranaweera",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.PURCHASE,
      price: 6000,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 10",
      description: "Gain a comprehensive understanding of the subject.",
      teacher: "Siriwardana Pradeep",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.PURCHASE,
      price: 5500,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 11",
      description: "Increase your skills with top-notch lessons.",
      teacher: "Kanchana Tharindu",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.PURCHASE,
      price: 4800,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 12",
      description: "Dive into advanced topics and boost your knowledge.",
      teacher: "Prasanna Dilshan",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.PURCHASE,
      price: 5200,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 13",
      description: "Start your journey to success with this course.",
      teacher: "Malini De Silva",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.PURCHASE,
      price: 4900,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 14",
      description: "Practical classes that help you learn efficiently.",
      teacher: "Pavithra Rajapaksha",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.PURCHASE,
      price: 4700,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 15",
      description: "Experience a complete learning process with this class.",
      teacher: "Chandana Kumara",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.PURCHASE,
      price: 5100,
    },
  ];
  
  export const studyPacks = [
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 1",
      description: "Learn with this class. Simple and effective.",
      teacher: "Saman Silva",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.STUDY,
      price: 5200,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 2",
      description: "Enhance your skills with detailed lessons.",
      teacher: "Kamal Perera",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.STUDY,
      price: 4500,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 3",
      description: "Achieve your goals with expert guidance.",
      teacher: "Nimal Fernando",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.STUDY,
      price: 6000,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 4",
      description: "Interactive and engaging classes for all.",
      teacher: "Amara Silva",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.STUDY,
      price: 3500,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 5",
      description: "Master new techniques with ease.",
      teacher: "Anushka Perera",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.STUDY,
      price: 4800,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 6",
      description: "Unlock your potential with this course.",
      teacher: "Ravi Kumar",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.STUDY,
      price: 5200,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 7",
      description: "Gain practical knowledge and hands-on experience.",
      teacher: "Ayesha Gomes",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.STUDY,
      price: 5600,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 8",
      description: "Advance your career with expert training.",
      teacher: "Sarath Nimal",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.STUDY,
      price: 4000,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 9",
      description: "Learn the secrets to success in your field.",
      teacher: "Himali Ranaweera",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.STUDY,
      price: 6000,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 10",
      description: "Gain a comprehensive understanding of the subject.",
      teacher: "Siriwardana Pradeep",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.STUDY,
      price: 5500,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 11",
      description: "Increase your skills with top-notch lessons.",
      teacher: "Kanchana Tharindu",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.STUDY,
      price: 4800,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 12",
      description: "Dive into advanced topics and boost your knowledge.",
      teacher: "Prasanna Dilshan",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.STUDY,
      price: 5200,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 13",
      description: "Start your journey to success with this course.",
      teacher: "Malini De Silva",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.STUDY,
      price: 4900,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 14",
      description: "Practical classes that help you learn efficiently.",
      teacher: "Pavithra Rajapaksha",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.STUDY,
      price: 4700,
    },
    {
      class_avatar: "https://picsum.photos/200/300",
      name: "Sample Class 15",
      description: "Experience a complete learning process with this class.",
      teacher: "Chandana Kumara",
      avatar: "https://picsum.photos/200/300",
      buttonType: ButtonType.STUDY,
      price: 5100,
    },
  ];
  